---
title: "Dissemination of Opinions in Social Networks"
author: "Johannes Nakayama"
date: "23 7 2020"
output: html_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(arrow)

```

```{r read-ba-data}

df <- tibble(
  Rep=integer(0), 
  Size=integer(0), 
  Culture=character(0), 
  SocialBotFrac=double(0),
  m0=integer(0)
)

ba_runs <- grep("barabasialbert", list.files("data"), value = TRUE) 

for (run in ba_runs) {
  df %>% 
    rbind(
      arrow::read_feather(
        file.path("data", run, "data", "agents", "adata.feather")
      )
    ) -> df
}

```



```{r}

df %>% 
  group_by(SocialBotFrac) %>% 
  summarise(n_part = n() / 3) -> df_reg_count

df_reg_count$SocialBotFrac <- as.numeric(as.character(df_reg_count$SocialBotFrac))

df_reg_count %>% 
  ggplot(aes(x = SocialBotFrac, y = n_part)) +
  geom_bar(stat = "identity", alpha = 0.8, fill = "navy") +
  scale_x_continuous(
    breaks = seq(0.00, 0.20, 0.01)
  ) +
  labs(
    x = "Fraction of Stubborn Agents",
    y = "Average Number of Regions",
    title = "Fragmentation in Barabási-Albert Graphs"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    panel.border = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.line = element_line(color = "black")
  )


```



```{r}

df %>% 
  group_by(SocialBotFrac, Rep) %>% 
  summarise(max_reg = max(Size)) -> df_big_reg

df_big_reg$max_reg <- as.numeric(df_big_reg$max_reg)

df_big_reg %>% 
  group_by(SocialBotFrac) %>% 
  summarize(avg_max_reg = mean(max_reg)) -> df_big_reg

df_big_reg$SocialBotFrac <- as.numeric(as.character(df_big_reg$SocialBotFrac))

df_big_reg %>% 
  ggplot(aes(x = SocialBotFrac, y = avg_max_reg)) +
  geom_bar(stat = "identity", alpha = 0.8, fill = "navy") +
  scale_x_continuous(
    breaks = seq(0.00, 0.20, 0.01)
  ) +
  labs(
    x = "Fraction of Stubborn Agents",
    y = "Average Size of Biggest Region",
    title = "Mean Size of Biggest Region in Barabási-Albert Graphs"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    panel.border = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.line = element_line(color = "black")
  )

```



```{r}

df %>% 
  filter(SocialBotFrac == 0.2) %>% 
  arrange(desc(Size))

```



```{r}

df %>% 
  filter(Rep == 1, SocialBotFrac == 0.15) %>% 
  group_by(Size) %>% 
  summarise(c = n())


```





```{r}

df2 <- tibble(
  Rep=integer(0), 
  Size=integer(0), 
  Culture=character(0), 
  SocialBotFrac=double(0),
  grid_height=integer(0)
)

grid_runs <- grep("grid", list.files("data"), value = TRUE) 

for (run in grid_runs) {
  df2 %>% 
    rbind(
      arrow::read_feather(
        file.path("data", run, "data", "agents", "adata.feather")
      )
    ) -> df2
}

```


```{r}

df2 %>% 
  group_by(SocialBotFrac) %>% 
  summarise(n_part = n() / 3) -> df2_reg_count

df2_reg_count$SocialBotFrac <- as.numeric(as.character(df2_reg_count$SocialBotFrac))

df2_reg_count %>% 
  ggplot(aes(x = SocialBotFrac, y = n_part)) +
  geom_bar(stat = "identity", alpha = 0.8, fill = "navy") +
  scale_x_continuous(
    breaks = seq(0.00, 0.20, 0.01)
  ) +
  labs(
    x = "Fraction of Stubborn Agents",
    y = "Average Number of Regions",
    title = "Fragmentation in Grid Graphs"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    panel.border = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.line = element_line(color = "black")
  )

```


```{r}

df2 %>% 
  group_by(SocialBotFrac, Rep) %>% 
  summarise(max_reg = max(Size)) -> df2_big_reg

df2_big_reg$max_reg <- as.numeric(df2_big_reg$max_reg)

df2_big_reg %>% 
  group_by(SocialBotFrac) %>% 
  summarize(avg_max_reg = mean(max_reg)) -> df2_big_reg

df2_big_reg$SocialBotFrac <- as.numeric(as.character(df2_big_reg$SocialBotFrac))

df2_big_reg %>% 
  ggplot(aes(x = SocialBotFrac, y = avg_max_reg)) +
  geom_bar(stat = "identity", alpha = 0.8, fill = "navy") +
  scale_x_continuous(
    breaks = seq(0.00, 0.20, 0.01)
  ) +
  labs(
    x = "Fraction of Stubborn Agents",
    y = "Average Size of Biggest Region",
    title = "Mean Size of Biggest Region in Grid Graphs"
  ) +
  theme_bw() +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
    panel.border = element_blank(),
    panel.grid.minor.x = element_blank(),
    axis.line = element_line(color = "black")
  )

```


```{r}

df2 %>% tail()

```


